import { CircleAlert, Cloud, HardDrive, KeyRound } from 'lucide-react';
import type { AiMode, AiSource } from '@/types/contracts';
import { cn } from '@/lib/cn';

type AiModeIndicatorProps = {
  /** Which client actually produced the result currently on screen. */
  activeSource: AiSource | null;
  /** Which upstream provider produced it, when the transport reported one. */
  activeProvider?: string | null;
  /** Providers that failed before the one that served the result. */
  failedOver?: readonly string[];
  configuredMode: AiMode;
  errored?: boolean;
  className?: string;
};

/** Display names for the providers the relay can reach. */
const PROVIDER_LABELS: Record<string, string> = {
  anthropic: 'Claude',
  openai: 'OpenAI',
  compatible: 'Custom',
};

function providerLabel(id: string | null | undefined): string | null {
  if (!id) return null;
  return PROVIDER_LABELS[id] ?? id;
}

/**
 * A discreet status pill.
 *
 * Its contract is strict: it reports which client ACTUALLY produced the result on screen, not
 * which one we hoped would. A "Live" badge sitting over an example response would be a lie.
 */
export function AiModeIndicator({
  activeSource,
  activeProvider,
  failedOver,
  configuredMode,
  errored = false,
  className,
}: AiModeIndicatorProps) {
  const state = describe(activeSource, configuredMode, errored);
  const provider = providerLabel(activeProvider);
  // Name the provider once one is known — "Live" alone is not specific enough when the relay can
  // fail over between providers.
  //
  // Deliberately NOT applied to the 'direct' source: that path sends the user's own key from the
  // browser, which is a materially different privacy situation from the server route, and
  // "Live · your key" is the more important thing to say. Naming the provider there would hide
  // the distinction the indicator exists to make.
  const label =
    provider && !errored && activeSource === 'proxy' ? `Live · ${provider}` : state.label;
  const failoverNote =
    failedOver && failedOver.length > 0
      ? ` Failed over from ${failedOver.map((id) => providerLabel(id) ?? id).join(', ')}.`
      : '';

  return (
    <span
      className={cn(
        'inline-flex min-h-tap items-center gap-2 rounded-chip border px-3 text-xs font-bold uppercase tracking-[0.09em]',
        state.classes,
        className,
      )}
      title={state.title + failoverNote}
    >
      <span className="relative flex h-1.5 w-1.5 shrink-0">
        <span className={cn('absolute inset-0 rounded-full', state.dot)} />
        {state.pulse ? (
          <span
            className={cn('absolute inset-0 rounded-full motion-safe:animate-ping', state.dot)}
          />
        ) : null}
      </span>
      <state.icon className="h-3.5 w-3.5" aria-hidden="true" />
      <span>{label}</span>
      <span className="sr-only">{state.title + failoverNote}</span>
    </span>
  );
}

function describe(activeSource: AiSource | null, configuredMode: AiMode, errored: boolean) {
  if (errored) {
    return {
      label: 'Error',
      icon: CircleAlert,
      classes: 'border-coral/45 bg-coral-soft text-coral-ink',
      dot: 'bg-coral',
      pulse: false,
      title: 'The last request failed. Nothing was substituted without asking you.',
    };
  }
  switch (activeSource) {
    case 'proxy':
      return {
        label: 'Live',
        icon: Cloud,
        classes: 'border-teal/45 bg-teal-soft text-teal-ink',
        dot: 'bg-teal',
        pulse: true,
        title:
          'Generated by the Anthropic API through the local server route. The key stays on the server.',
      };
    case 'direct':
      return {
        label: 'Live · your key',
        icon: KeyRound,
        classes: 'border-amber/45 bg-amber-soft text-amber-ink',
        dot: 'bg-amber',
        pulse: true,
        title:
          'Generated by the Anthropic API, called directly from this browser with the key you supplied.',
      };
    case 'fixture':
      return {
        label: 'Offline',
        icon: HardDrive,
        classes: 'border-primary/35 bg-primary-soft text-primary',
        dot: 'bg-primary',
        pulse: false,
        // Deliberately not "no network request was made": a live relay may have been tried and
        // declined first. What the badge is accountable for is where the words on screen came
        // from, and no model produced them.
        title: 'This came from a built-in example response. No AI generated it.',
      };
    default:
      return {
        label: 'Ready',
        icon: HardDrive,
        classes: 'border-line-strong bg-paper-sunk text-ink-muted',
        dot: 'bg-line-strong',
        pulse: false,
        title: `Nothing generated yet. Mode: ${configuredMode}.`,
      };
  }
}
